import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring, useTransform } from 'framer-motion';
import { ArrowDown, ArrowUpRight, ChevronRight, Compass, Heart, MapPin, Menu, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import './styles.css';
import './story.css';

const gateways=[
{id:'find',label:'FIND',title:'Find a Grave',copy:'Search by name, cemetery, or location. Navigate to the exact place and keep its story connected.',icon:MapPin,accent:'Places become stories.'},
{id:'plan',label:'PLAN',title:'Plan Your Legacy',copy:'Build the life instructions, people, provisions and wishes that should move forward with you.',icon:Compass,accent:'A future made clearer.'},
{id:'register',label:'REGISTER',title:'Register a Passing',copy:'Bring family, rites, records, places and responsibilities into one coordinated transition.',icon:Heart,accent:'When a life changes, everyone knows what comes next.'},
{id:'provide',label:'PROVIDE',title:'Provide for Those You Love',copy:'Turn care into structured provision for education, shelter, healthcare, milestones and family needs.',icon:Users,accent:'Care, made dependable.'}
];
const continuity=['Identity','People','Wishes','Documents','Provision','Places','Rites','Continuum'];
const prompts=['Emmanuel Okafor','Atan Cemetery','Fatimah Bello','my family','my wishes','protect my children'];
const story=[['01','A life begins','Every person has a story. RITES gives the people, places and things that matter a place to belong.'],['02','People gather around it','Family, friends, guardians, providers and communities become connected — with consent at the centre.'],['03','Life keeps becoming','Wishes, plans, documents, provisions and responsibilities change as life changes. RITES changes with them.'],['04','A transition happens','When something important changes, RITES brings the next people, decisions and responsibilities into view.'],['05','Love continues','What was built, promised, remembered and provided can continue — with the right people, at the right time.']];
const particleCount=72;
function ParticleField(){return <div className="particle-field" aria-hidden="true">{Array.from({length:particleCount}).map((_,i)=><i key={i} style={{'--x':`${(i*37)%101}%`,'--y':`${(i*61)%101}%`,'--s':`${2+(i%4)}px`,'--d':`${7+(i%9)}s`,'--delay':`${-(i%11)}s`}}/>)}<div className="mesh mesh-peach"/><div className="mesh mesh-blue"/><div className="mesh mesh-gold"/></div>}
function MagneticButton({children,className='',onClick}){const reduce=useReducedMotion();const x=useSpring(0,{stiffness:220,damping:22});const y=useSpring(0,{stiffness:220,damping:22});return <motion.button className={className} onClick={onClick} onPointerMove={e=>{if(reduce)return;const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-(r.left+r.width/2))*.08);y.set((e.clientY-(r.top+r.height/2))*.08)}} onPointerLeave={()=>{x.set(0);y.set(0)}} style={{x,y}}>{children}</motion.button>}
function App(){const reduce=useReducedMotion();const[active,setActive]=useState('find');const[query,setQuery]=useState('');const[open,setOpen]=useState(false);const[mobile,setMobile]=useState(false);const current=gateways.find(g=>g.id===active)||gateways[0];const Icon=current.icon;const{scrollY}=useScroll();const heroY=useTransform(scrollY,[0,700],[0,-95]);const heroScale=useTransform(scrollY,[0,700],[1,1.07]);const go=id=>{setActive(id);setMobile(false);document.getElementById('gateway')?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})};const reveal={hidden:{opacity:0,y:30},show:{opacity:1,y:0}};return <div className="rites">
<header className="header"><button className="logo" onClick={()=>window.scrollTo({top:0,behavior:reduce?'auto':'smooth'})}><span className="logo-mark"><i/><b/></span><span><strong>RITES</strong><small>HUMAN CONTINUITY PLATFORM</small></span></button><nav className={mobile?'nav nav-open':'nav'}>{gateways.map(g=><button key={g.id} className={active===g.id?'active':''} onClick={()=>go(g.id)}>{g.label}</button>)}<button onClick={()=>setOpen(true)}>INTELLIGENCE</button></nav><div className="header-actions"><button className="sign">Sign in</button><MagneticButton className="begin" onClick={()=>setOpen(true)}>Begin <ArrowUpRight size={16}/></MagneticButton><button className="hamb" onClick={()=>setMobile(v=>!v)}>{mobile?<X/>:<Menu/>}</button></div></header>
<main>
<section className="hero immersive-hero"><ParticleField/><motion.div className="hero-world" style={{y:heroY,scale:heroScale}}><div className="world-core"><span className="core-ring ring-a"/><span className="core-ring ring-b"/><span className="core-ring ring-c"/><span className="core-light"/><div className="core-label"><small>HUMAN CONTINUITY</small><strong>RITES</strong></div>{['PEOPLE','PLACES','WISHES','PROVISION','MEMORY','FUTURE'].map((x,i)=><span key={x} className={`world-node node-${i}`}>{x}</span>)}<svg className="world-lines" viewBox="0 0 600 600"><path d="M300 300C170 130 100 150 62 92M300 300C430 140 500 150 538 92M300 300C140 270 105 330 55 360M300 300C460 270 500 330 545 360M300 300C300 170 300 125 300 52M300 300C300 430 300 470 300 550"/></svg></div></motion.div><div className="hero-copy"><motion.div className="overline" initial={reduce?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.65}}>YOUR RITES. YOUR RULES. FROM BIRTH TO FOREVER.</motion.div><motion.h1 initial={reduce?false:{opacity:0,y:38,filter:'blur(12px)'}} animate={{opacity:1,y:0,filter:'blur(0px)'}} transition={{duration:1,ease:[.22,1,.36,1]}}>Where <em>love</em><br/>continues.</motion.h1><motion.p className="hero-lead" initial={reduce?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.18}}>A living continuity platform for the people, places, wishes, provisions and memories that make a life matter.</motion.p><div className={open?'search-hero expanded':'search-hero'}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>setOpen(true)} placeholder="Find a person, place, wish or begin..."/><MagneticButton className="search-action" onClick={()=>setOpen(true)}>Explore <ArrowUpRight size={16}/></MagneticButton></div><div className="prompt-row">{prompts.slice(0,3).map(p=><button key={p} onClick={()=>{setQuery(p);setOpen(true)}}>{p}</button>)}</div></div><div className="hero-scroll"><ArrowDown size={15}/><span>ENTER THE STORY</span></div></section>
<section className="story-intro"><motion.div variants={reveal} initial="hidden" whileInView="show" viewport={{once:true,amount:.4}}><span className="overline">A STORY, NOT A CHECKLIST</span><h2>Every life has<br/><em>a thread.</em></h2></motion.div><motion.p variants={reveal} initial="hidden" whileInView="show" viewport={{once:true,amount:.4}} transition={{delay:.12}}>RITES follows that thread — from the first people who hold us, through the places and promises we gather, to the moments when someone else needs to carry something forward.</motion.p><ArrowDown className="story-arrow" size={24}/></section>
<section className="story-scroll">{story.map(([n,t,c],i)=><motion.article key={n} className="story-card" initial={reduce?false:{opacity:0,y:55}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.35}} transition={{duration:.7}}><span>{n}</span><div><small>THE RITES STORY</small><h2>{t}</h2><p>{c}</p></div><div className="story-line"><i/></div></motion.article>)}</section>
<section className="stats-live"><div className="stats-orbit"/><div><strong>2.4M+</strong><span>Lives documented</span></div><div><strong>18,400</strong><span>Places mapped</span></div><div><strong>36</strong><span>States reached</span></div><div><strong>147K</strong><span>Families protected</span></div></section>
<section className="begin-section"><div className="section-heading"><span>BEGIN ANYWHERE</span><h2>Let the story<br/><em>lead you.</em></h2></div><div className="gateway-grid">{gateways.map(g=>{const G=g.icon;return <motion.button key={g.id} className={active===g.id?'gateway selected':'gateway'} onClick={()=>go(g.id)} whileHover={reduce?{}:{y:-8,rotateX:1}} transition={{type:'spring',stiffness:220,damping:25}}><div className="gateway-ambient"><span/><span/><span/></div><div className="gateway-content"><div className="gateway-icon"><G size={19}/></div><span>{g.label}</span><h3>{g.title}</h3><p>{g.copy}</p><b>{g.accent} <ArrowUpRight size={15}/></b></div></motion.button>})}</div></section>
<section className="gateway-detail" id="gateway"><AnimatePresence mode="wait"><motion.div key={current.id} className="detail-copy" initial={reduce?false:{opacity:0,x:-24}} animate={{opacity:1,x:0}} exit={reduce?undefined:{opacity:0,x:24}} transition={{duration:.45}}><div className="detail-icon"><Icon size={24}/></div><span className="overline">{current.label}</span><h2>{current.title}</h2><p>{current.copy}</p><MagneticButton className="gold-link" onClick={()=>setOpen(true)}>Begin {current.label.toLowerCase()} <ArrowUpRight size={16}/></MagneticButton></motion.div></AnimatePresence><div className="detail-art"><div className="detail-art-core"><Icon size={42}/><span>{current.label}</span></div><div className="detail-orbit orbit-1"/><div className="detail-orbit orbit-2"/></div></section>
<section className="continuum-section"><div><span className="overline">THE RITES PLATFORM</span><h2>One life.<br/><em>Many dimensions.</em></h2><p>People, places, decisions, documents, provisions and memories belong to the same story. RITES keeps the relationships visible.</p></div><div className="continuum-map">{continuity.map((item,i)=><motion.button key={item} className={`map-node n${i}`} onClick={()=>setOpen(true)} whileHover={reduce?{}:{scale:1.08}}>{item}</motion.button>)}<div className="map-center">YOU<small>CONTINUITY ROOT</small></div><svg viewBox="0 0 700 500" aria-hidden="true"><path d="M350 250 C180 120 110 180 90 80 M350 250 C520 120 600 190 620 85 M350 250 C190 330 120 390 75 430 M350 250 C510 330 580 390 635 430 M350 250 C350 120 350 70 350 30 M350 250 C350 380 350 420 350 475"/></svg></div></section>
<section className="ai-section"><div className="ai-glow"/><div className="ai-copy"><span className="overline">RITES INTELLIGENCE</span><h2>Tell RITES what matters.<br/><em>We'll map the rest.</em></h2><p>Voice-guided conversation turns natural language into structured continuity — people, wishes, provisions, records and transitions — without forcing you through forms first.</p><MagneticButton className="begin large" onClick={()=>setOpen(true)}>Begin a conversation <Sparkles size={16}/></MagneticButton></div><div className="voice-card"><div className="voice-top"><span>RITES VOICE</span><span>READY</span></div><div className="wave">{Array.from({length:28}).map((_,i)=><i key={i} style={{'--h':`${18+((i*17)%58)}px`}}/>)}</div><p>“I want my children to have what they need, and I want my wishes to be clear.”</p><div className="voice-footer"><Users size={16}/> People · Wishes · Provision · Future</div></div></section>
<section className="closing"><span className="overline">FROM BIRTH TO FOREVER</span><h2>What matters<br/><em>should continue.</em></h2><p>Start with a person, a place, a wish, a document or a responsibility. RITES grows around the life you are already living.</p><MagneticButton className="begin large" onClick={()=>setOpen(true)}>Begin RITES <ArrowUpRight size={17}/></MagneticButton></section></main>
<footer><div><strong>RITES</strong><span>Human continuity platform.</span></div><span>Your rites. Your rules. From birth to forever.</span></footer>
<AnimatePresence>{open&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}><motion.div className="drawer" initial={reduce?false:{y:45,opacity:0,scale:.98}} animate={{y:0,opacity:1,scale:1}} exit={reduce?undefined:{y:45,opacity:0}} transition={{type:'spring',damping:28}} onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="overline">RITES INTELLIGENCE</span><h2>Where would you like to begin?</h2></div><button onClick={()=>setOpen(false)}><X/></button></div><p>Start with a name, a place, a wish, a family question or anything you want RITES to help you organize.</p><div className="drawer-input"><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tell RITES what matters..."/></div><div className="drawer-prompts">{prompts.map(p=><button key={p} onClick={()=>setQuery(p)}>{p}<ChevronRight size={15}/></button>)}</div><div className="drawer-note"><ShieldCheck size={17}/><span>RITES is consent-first. Intelligence can prepare and explain; consequential actions remain under explicit authority.</span></div></motion.div></motion.div>}</AnimatePresence></div>}
createRoot(document.getElementById('root')).render(<App/>);
